services:
  texlive-ondemand-server:
    subdomain: compile
    port: 8080
    description: On-demand LaTeX compilation service
    env_file: texlive-ondemand-server.env

  y-webrtc-server:
    subdomain: sync
    port: 1234
    description: Y.js WebRTC signaling for collaborative editing
    env_file: y-webrtc-server.env

  filepizza-server:
    subdomain: files
    port: 8080
    description: Peer-to-peer file transfer service
    env_file: filepizza-server.env

  peerjs-server:
    subdomain: peer
    port: 9000
    description: PeerJS signaling server for WebRTC connections
    env_file: peerjs-server.env